### PR TITLE
Remove use of ::shadow, deprecated in Atom v1.13

### PR DESCRIPTION
**Pull request by adamrenklint**
Resolves https://github.com/olmokramer/atom-block-cursor/issues/33

### CODE REVIEW

**Comment by nelsonpecora** [comment]
yes please! this is totally broken in atom 1.13 with atom-block-cursor 0.13.1

**Comment by sm514a** [comment]
Thank you for this.

But, I got following message:
 Cannot find module 'object-assign-shim'

So, I tried deleting the dependency.
As far as I can see at a glance, it works without this package. 
Is 'object-assign-shim' package necessary?

**Comment by jorgefuertes** [comment]
Is urgently needed!

I did made the changes manually, as them are at this pull diff, and works fine for me.

**Comment by adamrenklint** [comment]
I've been in contact with Olmo, who is not using Atom or actively maintaining this repo anymore, and I will take over ownership of it ASAP, and then publish a new version. Subscribe to this PR to stay up to date.

**Comment by gotjoshua** [comment]
@adamrenklint do you still plan to take over the repo?

**Comment by adamrenklint** [comment]
@gotjoshua Yes, that's the plan. Gonna ping @olmokramer again about it.

**Pull request merged**
